#!/bin/sh

# Enable VNC clipboard
vncconfig -iconic &

# Set X window background
xsetroot -solid grey

# Run below programs for faster startup
xfce4-panel &
xfdesktop &

# Run complete xfce session
startxfce4 &
